-- Shared reference data for Restaurant Journal (restaurants, reviews, cities).
-- Per-user data (profiles, trips) is created by the app + the handle_new_user
-- trigger, not seeded here. Safe to re-run.
begin;
truncate table public.reviews, public.restaurants, public.destinations restart identity cascade;

-- restaurants
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-lisbon-01','Verde Talho','Lisbon','Portugal','Príncipe Real','{"Modern Portuguese","Vegetable-forward"}',3,0.8,38.7167,-9.1499,'verified-safe','2026-07-22','{"dairy","gluten","wheat","egg","soy","tree-nuts","peanuts"}','{"sesame","nightshades"}',true,true,true,true,true,'Chef-owned tasting spot that keeps a full allergen matrix per dish and will rebuild plates on request. Kitchen is used to coeliac and dairy-free guests and speaks to cross-contact without prompting.','{"Rice crackers with olive oil","Fresh fruit plate","Plain roast chicken"}',true,'Tue–Sat 18:00–23:00','+351 21 000 0001');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-lisbon-02','Casa do Arroz','Lisbon','Portugal','Alfama','{"Traditional Portuguese","Seafood"}',2,1.6,38.7139,-9.1275,'some-reports','2026-04-09','{"tree-nuts","peanuts","soy"}','{"dairy","gluten","wheat","shellfish","fish","egg"}',false,false,true,false,false,'Family-run rice and seafood house. Warm staff and dishes cooked to order, but shellfish and fish stock are used across the whole kitchen and there is one shared fryer. Best for nut-free and soy-free guests, risky for shellfish and gluten.','{"White rice","Orange segments"}',true,'Daily 12:00–15:00, 19:00–22:30','+351 21 000 0002');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-lisbon-03','Fresco & Cru','Lisbon','Portugal','Cais do Sodré','{"Salads","Juice bar","Raw"}',2,2.3,38.7058,-9.1449,'verified-safe','2026-08-01','{"dairy","gluten","wheat","egg","shellfish","fish","soy","sesame"}','{"tree-nuts","histamine","fermented"}',true,true,true,true,true,'Build-your-own bowl and juice bar with every ingredient labelled and staff trained on cross-contact. Naturally free of gluten, dairy, egg and shellfish. Watch the nut toppings and the fermented dressings if you react to histamine.','{"Cucumber & carrot sticks","Coconut yoghurt pot","Cold-pressed pear juice","Plain quinoa cup"}',true,'Mon–Sat 08:00–19:00','+351 21 000 0003');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-lisbon-04','Tasca Nova','Lisbon','Portugal','Graça','{"Petiscos","Wine bar"}',2,3.1,38.7223,-9.1303,'no-data',null,'{}','{}',false,false,false,false,false,'Popular natural-wine tasca. No allergy information has been collected yet and small plates are prepped ahead, so treat as unknown until someone reports back.','{}',false,'Wed–Sun 17:00–00:00',null);
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-cph-01','Rugbrød & Rod','Copenhagen','Denmark','Nørrebro','{"New Nordic","Smørrebrød"}',3,1.1,55.6949,12.5526,'some-reports','2026-05-19','{"tree-nuts","peanuts","shellfish","soy"}','{"gluten","wheat","dairy","fish","egg","histamine","fermented"}',false,false,false,false,true,'Seasonal smørrebrød with a rye-bread base on almost everything and a heavy hand with pickles, cured fish and aged cheese. Nut-free and shellfish-safe, but a hard place for gluten, dairy and histamine.','{"Boiled new potatoes","Apple slices"}',true,'Tue–Sat 11:30–21:00','+45 30 000 001');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-cph-02','Grøntsag','Copenhagen','Denmark','Vesterbro','{"Plant-based","Whole foods"}',3,2,55.6683,12.5533,'verified-safe','2026-08-15','{"dairy","egg","shellfish","fish","gluten","wheat","sesame"}','{"tree-nuts","soy","nightshades"}',true,true,true,true,true,'Entirely plant-based, so dairy, egg and seafood are off the table by design. Kitchen keeps a numbered allergen list, cooks each main to order, and has a printed low-histamine set menu on request.','{"Steamed edamame-free green beans","Baked sweet potato","Rice cakes with sunflower butter","Herbal tea"}',true,'Daily 17:00–22:00','+45 30 000 002');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-cph-03','Havn Grill','Copenhagen','Denmark','Havnegade','{"Grill","Steakhouse"}',4,3.4,55.6761,12.5911,'some-reports','2026-03-27','{"gluten","wheat","soy","sesame","tree-nuts","peanuts"}','{"dairy","shellfish","fish","histamine"}',false,false,true,false,false,'Charcoal grill focused on steak and whole fish. Naturally gluten- and nut-free for the mains, butter is used heavily on the grill and the dry-aged beef is a histamine problem. Kitchen will grill plain on request.','{"Grilled chicken skewer (no marinade)","Plain baked potato"}',false,'Wed–Sun 17:30–23:00','+45 30 000 003');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-kyoto-01','Shirakawa Kappō','Kyoto','Japan','Gion','{"Kaiseki","Japanese"}',4,0.9,35.0037,135.7788,'some-reports','2026-06-30','{"dairy","peanuts","nightshades"}','{"fish","shellfish","soy","gluten","wheat","sesame","egg","histamine","fermented"}',false,false,true,false,true,'Refined counter kaiseki. Dairy-free by tradition, but dashi (bonito + kombu), soy and mirin are in nearly every course, so fish, soy, gluten and histamine are hard to avoid. The chef will design an allergen-aware course with 3+ days notice.','{"Plain steamed rice","Simmered pumpkin"}',true,'Mon–Sat 18:00–22:00 (reservation only)','+81 75 000 0001');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-kyoto-02','Mame Shokudō','Kyoto','Japan','Nishiki','{"Shōjin ryōri","Vegan Japanese"}',2,1.8,35.0051,135.7649,'verified-safe','2026-08-20','{"dairy","egg","fish","shellfish","tree-nuts","peanuts","nightshades"}','{"soy","gluten","wheat","sesame","histamine","fermented"}',true,true,true,true,true,'Buddhist temple-style vegan cooking: no dairy, egg, fish, shellfish or animal stock anywhere in the kitchen. Uses a laminated English allergen chart. Soy and sesame are common but clearly marked, and there is a miso-free / low-histamine set on request.','{"Onigiri (salt only)","Steamed sweet potato","Kabocha nimono","Roasted barley tea"}',true,'Thu–Tue 11:00–20:00','+81 75 000 0002');
insert into public.restaurants (id,name,city,country,neighborhood,cuisine,price_level,distance_km,lat,lng,confidence,last_verified_at,safe_for_allergens,caution_allergens,accommodates_mcas,low_histamine_options,cooks_to_order,has_dedicated_allergen_menu,has_separate_fryer,summary,safe_snacks,open_now,hours,phone) values ('r-kyoto-03','Karasuma Curry Stand','Kyoto','Japan','Karasuma','{"Japanese curry","Casual"}',1,2.6,35.0116,135.7595,'no-data',null,'{}','{}',false,false,false,false,false,'Cheap, fast counter curry. Roux is pre-made and almost certainly contains wheat and dairy; no allergen information collected yet. Listed for completeness — treat as unknown.','{}',true,'Daily 11:00–21:00',null);

-- reviews
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-01-a','r-lisbon-01','Marta S.','2026-07-18','{"dairy","gluten","histamine"}',true,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Chef came to the table with the ingredient binder and flagged which sauces were aged. Built me a low-histamine plate with freshly seared fish and steamed greens. No reaction, no brain fog after.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-01-b','r-lisbon-01','Danielle P.','2026-06-02','{"tree-nuts","peanuts"}',false,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Nut-free kitchen for the night once I told them. Server knew the pesto had cashew and swapped it without me asking twice.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-01-c','r-lisbon-01','Kofi A.','2026-05-11','{"nightshades"}',false,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":false,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Most dishes lean on tomato and pepper so options were limited, but the kitchen was upfront about it and the two plates I could eat were excellent.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-02-a','r-lisbon-02','Ana R.','2026-03-30','{"gluten"}',false,3,'{"readFullIngredientList":true,"understoodCrossContact":false,"dedicatedPrepArea":false,"separateFryer":false,"chefOrManagerInvolved":true,"writtenAllergenInfo":false}'::jsonb,false,null,false,'Owner was kind and checked the rice was thickened without flour, but when I asked about the fryer he admitted everything goes in the same oil. I ate the grilled fish and rice and was fine, but I would not risk the fried stuff.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-02-b','r-lisbon-02','Tom H.','2026-02-14','{"shellfish"}',false,2,'{"readFullIngredientList":false,"understoodCrossContact":false,"dedicatedPrepArea":false,"separateFryer":false,"chefOrManagerInvolved":false,"writtenAllergenInfo":false}'::jsonb,true,'moderate',false,'Lips tingled after the rice even though I ordered the chicken one. Almost certainly cross-contact from the seafood rice they make in the same pans. Staff were apologetic but did not really get why it happened.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-03-a','r-lisbon-03','Priya K.','2026-07-29','{"dairy","egg","tree-nuts"}',true,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Every tub on the line has an allergen card. They changed gloves and used a fresh cutting board for my bowl without me having to push. Skipped the kimchi and the walnut topping and had zero issues.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-03-b','r-lisbon-03','Sofia L.','2026-06-20','{"histamine","fermented","citrus"}',true,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'They pointed me to the freshly cooked chicken, plain rice and steamed veg and made a dressing from olive oil and salt. Most of the menu is raw and citrus-heavy so it takes some navigating, but staff were patient.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-lisbon-03-c','r-lisbon-03','Ben C.','2026-05-05','{"gluten"}',false,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Coeliac-safe and quick. My go-to lunch when I stay in Lisbon.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-01-a','r-cph-01','Lena M.','2026-05-12','{"gluten","dairy"}',false,3,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":false,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":false}'::jsonb,false,null,true,'They could do two open sandwiches on gluten-free bread and used a clean board, but warned me the kitchen is small and the rye flour gets everywhere. I was fine but my partner with coeliac would not chance it.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-01-b','r-cph-01','Otto B.','2026-04-01','{"histamine","fermented"}',true,2,'{"readFullIngredientList":true,"understoodCrossContact":false,"dedicatedPrepArea":false,"separateFryer":false,"chefOrManagerInvolved":false,"writtenAllergenInfo":false}'::jsonb,true,'mild',false,'Almost everything is pickled, smoked or aged. Staff were friendly but did not really understand histamine. Flushed and headachy within the hour.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-02-a','r-cph-02','Priya K.','2026-08-10','{"dairy","egg","tree-nuts"}',true,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":true}'::jsonb,false,null,true,'The chef walked me through the low-histamine menu personally. Everything cooked fresh, nothing aged or fermented on my plates, nut station is separate. Best meal of the trip and I slept fine.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-02-b','r-cph-02','Marcus V.','2026-07-03','{"soy","gluten"}',false,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Soy shows up in a lot of the dishes as tofu or tamari, but they marked every one and had three soy-free mains. Gluten-free was no problem at all.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-02-c','r-cph-02','Hannah W.','2026-06-11','{"nightshades"}',true,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":false,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Asked them to leave out tomato and peppers and they adjusted two dishes happily. Paprika is in the house spice mix so double-check, but they knew that when I asked.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-03-a','r-cph-03','Ben C.','2026-03-20','{"dairy"}',false,3,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":false,"separateFryer":false,"chefOrManagerInvolved":true,"writtenAllergenInfo":false}'::jsonb,false,null,true,'They finish nearly everything with butter but the grill chef did my steak and veg with olive oil once the manager relayed it. Ask for the manager, not just the server.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-cph-03-b','r-cph-03','Otto B.','2026-02-08','{"histamine"}',true,2,'{"readFullIngredientList":true,"understoodCrossContact":false,"dedicatedPrepArea":false,"separateFryer":false,"chefOrManagerInvolved":false,"writtenAllergenInfo":false}'::jsonb,true,'moderate',false,'The whole menu is built on dry-aged beef and aged cheese. Fresh-cooked chicken was the only safe option and even that came with a red-wine jus on the side that touched the plate. Reacted badly.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-kyoto-01-a','r-kyoto-01','Yuki T.','2026-06-24','{"gluten","soy"}',false,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":false}'::jsonb,false,null,true,'Emailed ahead in Japanese with my allergy card text. The chef prepared a wheat-free, tamari-free course and explained each dish at the counter. Flawless, but it only works with advance notice.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-kyoto-01-b','r-kyoto-01','Sarah D.','2026-05-02','{"shellfish","fish"}',false,2,'{"readFullIngredientList":true,"understoodCrossContact":false,"dedicatedPrepArea":false,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":false}'::jsonb,false,null,false,'They were honest that a fish- and shellfish-free kaiseki is not something they can really do — dashi is the backbone of the whole meal. Appreciated the honesty but had to eat elsewhere.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-kyoto-02-a','r-kyoto-02','Marta S.','2026-08-16','{"dairy","gluten","histamine"}',true,5,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":true,"writtenAllergenInfo":true}'::jsonb,false,null,true,'They have a low-histamine set that skips miso, soy sauce and pickles — rare to find anywhere, let alone in Japan. Everything cooked fresh in front of you. I felt completely safe here.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-kyoto-02-b','r-kyoto-02','Yuki T.','2026-07-19','{"gluten","soy"}',false,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":true,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Soy is everywhere in shōjin cooking but the chart made it easy to pick around, and they had a wheat-free tamari. Two clearly-marked soy-free dishes plus rice made a full meal.');
insert into public.reviews (id,restaurant_id,author_name,visited_at,reviewer_allergens,reviewer_has_mcas,trust_rating,checklist,reaction_occurred,reaction_severity,would_return,comment) values ('rev-kyoto-02-c','r-kyoto-02','Elise F.','2026-06-05','{"sesame","tree-nuts"}',false,4,'{"readFullIngredientList":true,"understoodCrossContact":true,"dedicatedPrepArea":false,"separateFryer":true,"chefOrManagerInvolved":false,"writtenAllergenInfo":true}'::jsonb,false,null,true,'Sesame (goma) is in a lot of the dressings and tofu dishes. Staff knew exactly which and steered me to the simmered and grilled plates instead. Nut-free was no issue.');

-- destinations
insert into public.destinations (id,city,country,restaurant_count,blurb,sort_order) values ('dest-lisbon','Lisbon','Portugal',4,'Strong for gluten- and dairy-free; a few genuinely MCAS-aware kitchens.',0);
insert into public.destinations (id,city,country,restaurant_count,blurb,sort_order) values ('dest-cph','Copenhagen','Denmark',3,'Great plant-based scene, but a lot of pickled / cured / aged food to navigate.',1);
insert into public.destinations (id,city,country,restaurant_count,blurb,sort_order) values ('dest-kyoto','Kyoto','Japan',3,'Dairy-free is easy; dashi, soy and mirin make fish/soy/histamine hard.',2);
insert into public.destinations (id,city,country,restaurant_count,blurb,sort_order) values ('dest-barcelona','Barcelona','Spain',0,'No restaurants logged yet — be the first to add reports.',3);
insert into public.destinations (id,city,country,restaurant_count,blurb,sort_order) values ('dest-mexico-city','Mexico City','Mexico',0,'No restaurants logged yet — corn-heavy, worth mapping.',4);

commit;
