// Generated by Supabase: `supabase gen types typescript` (or MCP generate_typescript_types).
// Regenerate after any schema change. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      destinations: {
        Row: {
          blurb: string
          city: string
          country: string
          id: string
          restaurant_count: number
          sort_order: number
        }
        Insert: {
          blurb?: string
          city: string
          country: string
          id: string
          restaurant_count?: number
          sort_order?: number
        }
        Update: {
          blurb?: string
          city?: string
          country?: string
          id?: string
          restaurant_count?: number
          sort_order?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          additional_notes: string
          display_name: string
          id: string
          mcas_mode: boolean
          mcas_presets: Json
          preferred_card_language: string
          triggers: Json
          updated_at: string
        }
        Insert: {
          additional_notes?: string
          display_name?: string
          id: string
          mcas_mode?: boolean
          mcas_presets?: Json
          preferred_card_language?: string
          triggers?: Json
          updated_at?: string
        }
        Update: {
          additional_notes?: string
          display_name?: string
          id?: string
          mcas_mode?: boolean
          mcas_presets?: Json
          preferred_card_language?: string
          triggers?: Json
          updated_at?: string
        }
        Relationships: []
      }
      restaurants: {
        Row: {
          accommodates_mcas: boolean
          caution_allergens: string[]
          city: string
          confidence: string
          cooks_to_order: boolean
          country: string
          created_at: string
          cuisine: string[]
          distance_km: number
          has_dedicated_allergen_menu: boolean
          has_separate_fryer: boolean
          hours: string
          id: string
          last_verified_at: string | null
          lat: number
          lng: number
          low_histamine_options: boolean
          name: string
          neighborhood: string
          open_now: boolean
          phone: string | null
          price_level: number
          safe_for_allergens: string[]
          safe_snacks: string[]
          summary: string
        }
        Insert: {
          accommodates_mcas?: boolean
          caution_allergens?: string[]
          city: string
          confidence?: string
          cooks_to_order?: boolean
          country: string
          created_at?: string
          cuisine?: string[]
          distance_km?: number
          has_dedicated_allergen_menu?: boolean
          has_separate_fryer?: boolean
          hours?: string
          id: string
          last_verified_at?: string | null
          lat?: number
          lng?: number
          low_histamine_options?: boolean
          name: string
          neighborhood?: string
          open_now?: boolean
          phone?: string | null
          price_level?: number
          safe_for_allergens?: string[]
          safe_snacks?: string[]
          summary?: string
        }
        Update: {
          accommodates_mcas?: boolean
          caution_allergens?: string[]
          city?: string
          confidence?: string
          cooks_to_order?: boolean
          country?: string
          created_at?: string
          cuisine?: string[]
          distance_km?: number
          has_dedicated_allergen_menu?: boolean
          has_separate_fryer?: boolean
          hours?: string
          id?: string
          last_verified_at?: string | null
          lat?: number
          lng?: number
          low_histamine_options?: boolean
          name?: string
          neighborhood?: string
          open_now?: boolean
          phone?: string | null
          price_level?: number
          safe_for_allergens?: string[]
          safe_snacks?: string[]
          summary?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          author_name: string
          checklist: Json
          comment: string
          created_at: string
          id: string
          reaction_occurred: boolean
          reaction_severity: string | null
          restaurant_id: string
          reviewer_allergens: string[]
          reviewer_has_mcas: boolean
          trust_rating: number
          user_id: string | null
          visited_at: string
          would_return: boolean
        }
        Insert: {
          author_name: string
          checklist?: Json
          comment?: string
          created_at?: string
          id: string
          reaction_occurred?: boolean
          reaction_severity?: string | null
          restaurant_id: string
          reviewer_allergens?: string[]
          reviewer_has_mcas?: boolean
          trust_rating: number
          user_id?: string | null
          visited_at: string
          would_return?: boolean
        }
        Update: {
          author_name?: string
          checklist?: Json
          comment?: string
          created_at?: string
          id?: string
          reaction_occurred?: boolean
          reaction_severity?: string | null
          restaurant_id?: string
          reviewer_allergens?: string[]
          reviewer_has_mcas?: boolean
          trust_rating?: number
          user_id?: string | null
          visited_at?: string
          would_return?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "reviews_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      trips: {
        Row: {
          country: string
          created_at: string
          destination: string
          end_date: string
          id: string
          notes: string
          saved_restaurant_ids: string[]
          start_date: string
          status: string
          user_id: string
        }
        Insert: {
          country: string
          created_at?: string
          destination: string
          end_date: string
          id: string
          notes?: string
          saved_restaurant_ids?: string[]
          start_date: string
          status?: string
          user_id: string
        }
        Update: {
          country?: string
          created_at?: string
          destination?: string
          end_date?: string
          id?: string
          notes?: string
          saved_restaurant_ids?: string[]
          start_date?: string
          status?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
